id: IE33E8662
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T05:09:54+00:00'
last_modified: '2022-06-13T12:46:19.961232+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30416
  title: མི་ཉག་འཇམ་དབྱངས་གྲགས་པའི་རང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7864':
      image_group_id: I1PD28133
      title: ''
      total_pages: ''
      order: 1
      base_file: 7864.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
